[theme]
primaryColor = "#325aff"
backgroundColor = "#ffffffa5"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
baseRadius = "none"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false